gics/gics/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from gics.views import MarkdownView, SchoolList, SessionList, SchoolDetail, LectureList, LectureDetail, NewsList, NewsDetail, QuestionList, DisciplineDetail
from wiki.urls import get_pattern as get_wiki_pattern
from django_nyt.urls import get_pattern as get_nyt_pattern

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gics.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'gics.views.index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^page/(?P<slug>[\w/-]+)/$', MarkdownView.as_view()),
    url(r'^page/(?P<slug>[\w/-]+)/$', MarkdownView.as_view()),
    url(r'^lycees/$', SchoolList.as_view(), name='school-list'),
    url(r'^lycees/(?P<pk>\d+)$', SchoolDetail.as_view(), name='school-detail'),
    url(r'^ateliers/$', LectureList.as_view()),
    url(r'^ateliers/(?P<pk>\d+)$', LectureDetail.as_view()),
    url(r'^ateliers/(?P<slug>\w+)/$', DisciplineDetail.as_view()),
    url(r'^news/$', NewsList.as_view()),
    url(r'^news/(?P<pk>\d+)$', NewsDetail.as_view()),
    url(r'^contact/$', 'gics.views.contact'),
    url(r'^register/$', 'gics.views.register'),
    url(r'^faq/$', QuestionList.as_view()),
    url(r'^forum/$', 'gics.views.forum'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^notifications/', get_nyt_pattern()),
    url(r'^wiki/', get_wiki_pattern()),
    url(r'^(?P<slug>[\w-]+)/$', 'gics.views.follow_alias'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gics/gics/models.py
# coding=utf8
from django.db import models
from django.contrib.auth.models import User
from secret import MAIL_CHOICES


class UserProfile(models.Model):  # Garantir le lien
    user = models.OneToOneField(User)
    school = models.ForeignKey('School')
    school_year = models.CharField(max_length=32)
    newsletter = models.BooleanField(default=True)


class Person(models.Model):
    user = models.OneToOneField(User, blank=True, null=True)
    first_name = models.CharField(max_length=64)
    surname = models.CharField(max_length=64, blank=True, null=True)
    phone_number = models.CharField(max_length=64, blank=True, null=True)
    comments = models.TextField(blank=True, null=True)
    mail = models.CharField(max_length=128)
    school = models.ForeignKey('School', blank=True, null=True)
    majors = models.ManyToManyField('Discipline', blank=True)
    status = models.CharField(max_length=15, default='speaker', choices=(
        ('member', 'Membre adhérent'),
        ('speaker', 'Simple intervenant'),
        ('former', 'Ancien membre ou intervenant')
    ))
    has_priority = models.BooleanField(default=False)
    favorite_schools = models.ManyToManyField('School', related_name='favorited', blank=True)
    address = models.TextField(blank=True, null=True)
    def __str__(self):
        return self.first_name if not self.surname else '%s %s' % (self.first_name, self.surname)
    def get_name(self):
        return str(self)
    class Meta:
        ordering = ['first_name']
        verbose_name_plural = 'people'


class Note(models.Model):
    content = models.CharField(max_length=128)
    date = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.content


class UserHistory(models.Model):
    user = models.ForeignKey(Person)
    date = models.DateField()
    action = models.CharField(max_length=15, choices=(
        ('ping', 'Contacté(e)'),
        ('pong', 'A répondu'),
        ('joined', 'Adhésion'),
        ('quit', 'Démission'),
        ('fired', 'Radiation'),
        ('offered', 'Don')
    ))
    donation = models.DecimalField(max_digits=16, decimal_places=2, default=0)
    school = models.ForeignKey('School', blank=True, null=True)
    def __str__(self):
        return '%s %s' % (self.user, self.action)
    class Meta:
        ordering = ['-date']
        verbose_name_plural = "user histories"


class School(models.Model):
    title = models.CharField(max_length=64)
    address = models.TextField(blank=True, null=True)
    postal_code = models.CharField(max_length=5, blank=True, null=True)
    city = models.CharField(max_length=32, blank=True, null=True)
    manager = models.ForeignKey(User, blank=True, null=True)
    school_type = models.CharField(max_length=11, choices=(
        ('highschool', 'Lycée'),
        ('institution', 'Institution'),
    ), default='institution')
    picture = models.ForeignKey('Document', blank=True, null=True)
    def __str__(self):
        return self.title


class Discipline(models.Model):
    slug = models.SlugField(max_length=64)
    title = models.CharField(max_length=64)
    def __str__(self):
        return self.title


class Lecture(models.Model):
    discipline = models.ManyToManyField(Discipline, blank=True)  # Tags ou disciplines ?
    title = models.CharField(max_length=64)
    description = models.TextField()
    poster = models.CharField(max_length=32, default='', blank=True)
    links = models.TextField(default='', blank=True)
    def __str__(self):
        return self.title
    def get_discipline_slugs(self):
        slugs = []
        for discipline in self.discipline.all():
            slugs.append(discipline.slug)
        return ' ' + ' '.join(slugs)


class Session(models.Model):
    lecture = models.ForeignKey('Lecture')
    school = models.ForeignKey('School')
    date = models.DateTimeField()
    speaker = models.ForeignKey(Person)
    details = models.TextField(default='', blank=True)
    slot_defined = models.BooleanField(default=False)
    media_printed = models.BooleanField(default=False)
    feedback_collected = models.BooleanField(default=False)
    debrief_done = models.BooleanField(default=False)
    def __str__(self):
        return self.lecture.title

    class Meta:
        ordering = ['date']


class News(models.Model):
    title = models.CharField(max_length=64)
    date = models.DateTimeField()
    author = models.ForeignKey(User)
    content = models.TextField()
    def __str__(self):
        return self.title
    class Meta:
        verbose_name_plural = "news"


class Page(models.Model):
    name = models.SlugField()
    markdown = models.TextField()
    def __str__(self):
        return self.name


class Document(models.Model):
    content = models.FileField(upload_to='files')
    def __str__(self):
        return self.content.name


class Question(models.Model):
    statement = models.CharField(max_length=512)
    answer = models.TextField()
    def __str__(self):
        return self.statement


def to_form(choices):
    return [(choice_id, choice_name) for choice_id, choice_name, _ in choices]


class Contact(models.Model):
    action = models.CharField(max_length=32, choices=to_form(MAIL_CHOICES), default='default', verbose_name='Que souhaitez-vous faire ?')
    name = models.CharField(max_length=128, verbose_name='Votre nom complet')
    email = models.CharField(max_length=128, verbose_name='Votre mail')
    message = models.TextField(verbose_name='Votre message')


class Alias(models.Model):
    slug = models.SlugField(unique=True)
    path = models.CharField(max_length=32)

gics/gics/forms.py
from django import forms
from captcha.fields import CaptchaField
from gics.models import Contact


class ContactForm(forms.ModelForm):
    captcha = CaptchaField(label='Entrez le code')

    class Meta:
        model = Contact
        fields = ['action', 'name', 'email', 'message']

gics/gics/views.py
# coding=utf-8
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponse, Http404
from django.core.mail import send_mail
from gics.models import News, Session, Page, School, Session, Lecture, Question, Discipline, Note, Person, Alias
from gics.forms import ContactForm
from datetime import datetime
from markdown import markdown
from secret import MAIL_CHOICES
import re

def index(request):
    return render(request, 'index.html', {
        'nb_sessions': 121, # Session.objects.count(),
        'nb_schools': School.objects.filter(school_type='highschool').count(),
        'nb_users': Person.objects.count(),
        'news_list': News.objects.order_by('-date')[:5],
        'mail_choices': MAIL_CHOICES,
        'form': ContactForm()
        # 'next_sessions': Session.objects.filter(date__gt=datetime.now()).order_by('date')[:5]
    })

def contact(request):
    done = False
    if request.POST:
        form = ContactForm(request.POST)
        if not form.is_valid():
            messages.error(request, 'Veuillez remplir tous les champs correctement')
        else:
            from_mail = form.cleaned_data.get('email')
            to_mail = None
            for choice_id, _, mail in MAIL_CHOICES:
                if choice_id == form.cleaned_data.get('action'):
                    to_mail = mail
            send_mail('[Contact] GICS', '%s <%s> a envoyé un message via le site :\n\n%s' % (form.cleaned_data.get('name'), from_mail, form.cleaned_data.get('message')), from_mail, [to_mail], fail_silently=True)
            messages.success(request, 'Votre message a bien été envoyé. Nous vous répondrons au plus vite.')
            done = True
    else:
        form = ContactForm()
    return render(request, 'contact.html', {
        'form': form,
        'done': done,
        'mail_choices': MAIL_CHOICES
    })

def register(request):
    context = {}
    if request.POST:
        contacts = request.POST.get('contacts').strip().split('\n')
        re_mail = re.compile(r'\b([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})\b')
        re_name = re.compile(r'([^ ]+) +$')
        re_number = re.compile(r'([0-9]{2}[\. ]?[0-9]{2}[\. ]?[0-9]{2}[\. ]?[0-9]{2}[\. ]?[0-9]{2})')
        added_contacts = []
        errors = []
        for line in contacts:
            Note(content=line).save()
            contact = {}
            has_mail = re_mail.search(line)
            if has_mail:
                contact['mail'] = has_mail.group(1)
                first, second = line.split(contact['mail'])
                has_number = re_number.search(second)
                if has_number:
                    contact['phone_number'] = has_number.group(1)
                    contact['comments'] = second.replace(contact['phone_number'], '').strip()
                else:
                    has_number = re_number.search(first)
                    if has_number:
                        contact['phone_number'] = has_number.group(1)
                        contact['comments'] = second.strip()
                        first = first.replace(contact['phone_number'], '')
            else:
                has_number = re_number.search(line)
                if has_number:
                    contact['phone_number'] = has_number.group(1)
                    first, second = line.split(contact['phone_number'])
                    contact['comments'] = second.strip()
                else:
                    errors.append(line)
                    continue  # I give up with this line (couldn't find either mail or phone number)
            has_name = re_name.search(first)
            if has_name:
                name = has_name.group(1)
                remainder = first.replace(name, '').strip()
                if remainder:
                    contact['first_name'] = remainder
                    contact['surname'] = name
                else:
                    contact['first_name'] = name
            Person(**contact).save()
            full_name = ('%s %s' % (contact['first_name'], contact.get('surname', ''))).strip()
            added_contacts.append(full_name)
        context['message'] = u'Contacts ajoutés (%d) :<br />' % len(added_contacts)
        for name in added_contacts:
            context['message'] += '- %s<br />' % name
        if errors:
            print(errors)
            context['message'] += '<br />Erreur pour les lignes suivantes (%d) :<br />' % (len(errors))
            for line in errors:
                context['message'] += '- %s<br />' % line
    return render(request, 'register.html', context)

def faq(request):
    return render(request, 'faq.html', {
        'news_list': News.objects.order_by('-date')[:5],
        'next_sessions': Session.objects.filter(date__gt=datetime.now()).order_by('date')[:5]
    })

def forum(request):
    return render(request, 'forum.html', {
        'news_list': News.objects.order_by('-date')[:5],
        'next_sessions': Session.objects.filter(date__gt=datetime.now()).order_by('date')[:5]
    })

class MarkdownView(DetailView):
    model = Page
    slug_field = 'name'
    template_name = 'static.html'
    """def get_object(self):
        try:
            return super(MarkdownView, self).get_object()
        except Http404:
            Page(name=self.kwargs['slug'], markdown='').save()  # Create the page if it does not exist
            raise Http404"""
    def get_context_data(self, **kwargs):
        page = super(MarkdownView, self).get_object()
        context = {
            'name': page.name,
            'html': markdown(page.markdown),
            'next_sessions': Session.objects.filter(date__gt=datetime.now()).order_by('date')[:5],
            'mail_choices': MAIL_CHOICES,
        }
        if page.name == 'devenir-intervenant':
            context['form'] = ContactForm()
        return context

class SchoolList(ListView):
    def get_queryset(self):
        return School.objects.filter(school_type='highschool')
    model = School

class SchoolDetail(DetailView):
    model = School

class SessionList(ListView):
    model = Session

class LectureList(ListView):
    model = Lecture
    def get_queryset(self):
        return super(LectureList, self).get_queryset().order_by('title')
    def get_context_data(self, **kwargs):
        context = super(LectureList, self).get_context_data()
        context['disciplines'] = Discipline.objects.all()
        return context

class LectureDetail(DetailView):
    model = Lecture

class NewsList(ListView):
    model = News
    def get_queryset(self):
        return super(NewsList, self).get_queryset().order_by('-date')

class NewsDetail(DetailView):
    model = News

class QuestionList(ListView):
    model = Question

class DisciplineDetail(DetailView):
    model = Discipline

def follow_alias(request, slug):
    alias = get_object_or_404(Alias, slug=slug)
    return redirect('/' + alias.path)

gics/gics/templates/gics/discipline_detail.html
{% extends "base.html" %}

{% block body %}
<div class="static l-box pure-g">
    <div class="pure-u-1 pure-u-md-1 pure-u-lg-1-5"></div>
    <div class="pure-u-1 pure-u-md-1 pure-u-lg-3-5">
        <h1>Ateliers de {{ object|lower }}</h1>
        <ul>
        {% for lecture in object.lecture_set.all %}
            <li><a href="/ateliers/{{ lecture.id }}"><strong>{{ lecture.title }}</strong></a></li>
        {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

{% block aside %}
{% endblock %}

gics/gics/templates/gics/lecture_detail.html
{% extends "base.html" %}

{% block body %}
<div class="static l-box pure-g">
    <div class="pure-u-1 pure-u-md-1 pure-u-lg-1-5"></div>
    <div class="pure-u-1 pure-u-md-1 pure-u-lg-3-5">
        <h1>{{ object.title }}</h1>
        <hr />
        Disciplines :
        {% for discipline in object.discipline.all %}
            <a href="/ateliers/{{ discipline.slug }}/">{{ discipline }}</a>
        {% endfor %}
        <p class="well">{{ object.description|safe }}</p>
        {% if object.links %}
            <h2>Liens</h2>
            {{ object.links|safe }}
        {% endif %}
        <h2>Séances</h2>
        {% for session in object.session_set.all %}
            {{ session.school }}, le {{ session.date }} par {{ session.speaker }}
        {% empty %}
            Il n'y a pas encore de séance prévue pour cet atelier.
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block aside %}
{% endblock %}

gics/gics/templates/gics/lecture_list.html
{% extends "base.html" %}

{% block body %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.2.2/isotope.pkgd.js"></script>
<div class="static l-box pure-g">
    <div class="pure-u-1 pure-u-md-1 pure-u-lg-1-5"></div>
    <div class="pure-u-1 pure-u-md-1 pure-u-lg-3-5">
        <h1>Ateliers</h1>
        Filtrer :<br />
        <input type="checkbox" id="checker" checked value="tout décocher" /> Tout cocher ?
        <hr />
        <div id="disciplines">
        {% for discipline in disciplines %}
            <label><input type="checkbox" value="{{ discipline.slug }}" checked onclick="updateLectures()"> {{ discipline }}</label> 
        {% endfor %}
        </div>
        <hr />
        <ul class="grid">
        {% for lecture in object_list %}
            <li class="grid-item{{ lecture.get_discipline_slugs }}"><a href="/ateliers/{{ lecture.id }}"><strong>{{ lecture.title }}</strong></a></li>
        {% endfor %}
        </ul>
    </div>
</div>
<script>
// $('.grid').isotope({ filter: '.{{ discipline.slug }}' })
function updateLectures() {
  choices = $('#disciplines :checked').map(function() {return '.' + this.value}).get();
  $('.grid').isotope({ filter: choices.join(',') })
}

$('.grid').isotope({
  // options
  itemSelector: '.grid-item',
  layoutMode: 'vertical'
});

$("#checker").change(function () {
  $("input:checkbox").prop('checked', $(this).prop("checked"));
  updateLectures();
});
</script>
{% endblock %}

{% block aside %}
{% endblock %}

gics/gics/templates/gics/news_list.html
{% extends "base.html" %}

{% block body %}
<div class="static l-box pure-g">
    <div class="pure-u-1 pure-u-md-1 pure-u-lg-1-5"></div>
    <div class="pure-u-1 pure-u-md-1 pure-u-lg-3-5">
        {% for news in object_list %}
        <article>
            <h1>{{ news.title }}</h1>
            <span class="author">Par {{ news.author.first_name }} {{ news.author.last_name }} - Le {{ news.date }}</span>
            <p>{{ news.content|safe }}</p>
        </article>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block aside %}
{% endblock %}

gics/gics/templates/gics/question_list.html
{% extends "base.html" %}

{% block body %}
<div class="static l-box pure-g">
    <div class="pure-u-1 pure-u-md-1 pure-u-lg-1-5"></div>
    <div class="pure-u-1 pure-u-md-1 pure-u-lg-3-5">
        <h2 class="content-head is-center">FAQ</h2>
        {% for question in object_list %}
            <h3>{{ question.statement }}</h3>
            {{ question.answer|safe }}
        {% endfor %}
    </div>
</div>
{% endblock %}

gics/gics/templates/gics/school_detail.html
{% extends "base.html" %}

{% block body %}
<div class="static l-box pure-g">
    <div class="pure-u-1 pure-u-md-1 pure-u-lg-1-5"></div>
    <div class="pure-u-1 pure-u-md-1 pure-u-lg-3-5">
        <div class="pure-g">
            <div class="pure-u-1 pure-u-md-1 pure-u-lg-1-2">
                <h1>{{ object.title }}</h1>
                <address>
                    {{ object.address }}<br />
                    {{ object.postal_code }} {{ object.city }}
                </address>
            </div>
            <div class="pure-u-1 pure-u-md-1 pure-u-lg-1-2">
                {% if object.picture %}
                <figure>
                    <img src="/media/{{ object.picture }}" alt="illustration {{ object.title }}" />
                </figure>            
                {% endif %}
            </div>
        </div>
        <br />
        Responsable lycée : {{ object.manager.first_name }} {{ object.manager.last_name }}

        <h2>Séances</h2>
        <ul>
        {% for session in object.session_set.all %}
            <li><a href="/ateliers/{{ session.lecture.id }}">{{ session }}</a> par {{ session.speaker }}<br />
            {{ session.date }}<hr /></li>
        {% empty %}
            Il n'y a pas de séance pour le moment.
        {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

{% block aside %}
{% endblock %}

gics/gics/templates/gics/school_list.html
{% extends "base.html" %}

{% block body %}
<div class="static l-box pure-g">
    <div class="pure-u-1 pure-u-md-1 pure-u-lg-1-5"></div>
    <div class="pure-u-1 pure-u-md-1 pure-u-lg-3-5">
        <h1>Lycées partenaires</h1>
        <ul>
        {% for school in object_list %}
            <li><a href="{% url "school-detail" school.id %}">{{ school.title }}</a></li>
        {% endfor %}
        </ul>
        <h2>Écoles partenaires</h2>
        <ul>
            <li>Centrale Paris</li>
            <li>École normale supérieure</li>
            <li>École normale supérieure de Cachan</li>
            <li>École polytechnique</li>
            <li>Université Paris 6 – Pierre et Marie Curie</li>
        </ul>
    </div>
</div>
{% endblock %}

{% block aside %}
{% endblock %}

gics/gics/templates/gics/session_list.html
{% extends "base.html" %}

{% block body %}
<div class="static l-box pure-g">
    <div class="pure-u-1 pure-u-md-1 pure-u-lg-1-5"></div>
    <div class="pure-u-1 pure-u-md-1 pure-u-lg-3-5">
        <h1>Prochains ateliers</h1>
        {% for session in object_list %}
        <hr />
        <article>
            <h3>{{ session.lecture.title }}</h3>
            <h4>Le {{ session.date }} – {{ session.school }}</h4>
            <span class="author">Par {{ session.speaker.first_name }} {{ session.speaker.last_name }}</span>
            <p class="well">{{ session.lecture.description|safe }}</p>
        </article>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block aside %}
{% endblock %}